### ISSUE TITLE
2017 conference talk

### ISSUE THREAD

**Issue by simlei** [diffplug/gradle_and_eclipse_rcp#10]
Hi @nedtwigg , I was wondering whether there is a recording of the talk on this project. I found your SwtRx talk very instructive and would love to see this one, too. Nice to pick the xkcd colors experiment as demo there by the way!

**Comment by nedtwigg** [comment]
Thanks, glad they're useful!

The slides and video for this talk at different times are [here](https://github.com/diffplug/gradle-and-eclipse-rcp#talks).
