### ISSUE TITLE
Please provide simple example with e4 application model

### ISSUE THREAD

**Issue by MarceloRuiz** [diffplug/gradle_and_eclipse_rcp#12]
Hi,
I am wondering if it will be possible to a simple example using the e4 application model (root project and subproject providing Application.e4xmi).
I tried configuring a project based on the example, but I get all sort of errors in Eclipse (not a java project, not a source folder, and so on) that prevent me from even creating a single class file.
Thanks

**Comment by nedtwigg** [comment]
We'd be happy to accept a PR for something like this, but building this won't make the top of our todo list.

**Comment by MarceloRuiz** [comment]
Just to understand the situation: is building an e4 project with Gradle currently possible? When you talk about building this I don't know if you mean the example or functionality to make that example possible?

**Comment by nedtwigg** [comment]
There are users building e4 projects with this plugin.  For someone fluent in e4, it should be a quick job to turn this example project into an example with `Application.e4xmi`.

Learning multiple things at once is tricky.  I would advise:

- run this gradle example as-is
- run an e4 example from somewhere else as-is
- migrate the e4 example into this gradle example

**Comment by MarceloRuiz** [comment]
Thanks for your suggestion. I have a basic e4 project but its based on e(fx)clipse, so it adds another level of complication.
[Edit] I actually found an old project: https://github.com/mcmil/wuff-efxclipse-samples. I guess switching from the wuff-only build might be easier to do...
