### ISSUE TITLE
artifacts.xml errors when trying to build

### ISSUE THREAD

**Issue by reinsch82** [diffplug/gradle_and_eclipse_rcp#13]
I get `C:\Users\R65C8~1.DEG\AppData\Local\Temp\2\goomph-ant-build154402244610777679.xml:2: org.eclipse.equinox.p2.core.ProvisionException: Unable to connect to repository http://download.eclipse.org/eclipse/updates/4.6/R-4.6.2-201611241400/artifacts.xml`

Which sort of makes sense as  `artifacts.xml` is not there but `artifacts.xml.xz` would be

**Comment by nedtwigg** [comment]
Can you provide more info so I can reproduce?  Are you using latest version of `goomph`?  How have you modified the template?

**Comment by reinsch82** [comment]
I used the repo as-is on the first try and started gradlew build. 
After that I tried upgrading goomph to 3.16 and the eclipse platform to 4.7.
Does the xml vs xml.xz make sense? 
Thx

**Comment by nedtwigg** [comment]
> I used the repo as-is on the first try and started gradlew build.

Did that work?

> After that I tried upgrading goomph to 3.16 and the eclipse platform to 4.7.

Can you post the whole stacktrace?

**Comment by reinsch82** [comment]
No as-is didn't work.
I'll try again on another network at home so I can rule out company network issues.

**Comment by nedtwigg** [comment]
Roger.  The `xml` vs `xml.xz` on its own doesn't make sense, because I believe it checks a few different extensions.  It might be that the error is only thrown on the last attempt.  If a plain checkout didn't work, then I'd suspect network issues.

**Comment by reinsch82** [comment]
It seems to be network related, will investigate further tomorrow.
At home it worked right away

**Comment by reinsch82** [comment]
It seems not to work with a proxy.
Any idea how to make it work with a proxy?
I tried the _JAVA_OPTIONS to set http(s)Proxy and ports

**Comment by nedtwigg** [comment]
I'd try digging through [these](https://github.com/diffplug/goomph/search?q=proxy&type=Issues).

**Comment by reinsch82** [comment]
thx
the proxies.ini work around seems to work
But I had to add an `it.` to the example here: https://diffplug.github.io/goomph/javadoc/3.3.0/com/diffplug/gradle/p2/AsMavenPlugin.html
`p2ant {
           it.addArg('plugincustomization', '<path to proxies.ini>')
        }`

**Comment by nedtwigg** [comment]
Great, glad it was resolved!  How'd you reach that link to the `3.3.0` docs?  The latest docs have the `it.` already included: https://diffplug.github.io/goomph/javadoc/3.16.0/com/diffplug/gradle/p2/AsMavenPlugin.html

**Comment by reinsch82** [comment]
ups
google showed me that link
I think I searched for "p2ant"
