### ISSUE TITLE
Will this support latest JDK 17

### ISSUE THREAD

**Issue by zeefahs13** [diffplug/gradle_and_eclipse_rcp#19]
Is the gradle used in this project upgraded in accordance with new JDK 17 ? Is there us any plan? Eclipse will no longer supports PDE Will this work even after it?

**Comment by nedtwigg** [comment]
Happy to take a PR for it. Goomph definitely works with JDK 17, but we are not proactively updating this demo project anymore.

**Comment by zeefahs13** [comment]
> Happy to take a PR for it. Goomph definitely works with JDK 17, but we are not proactively updating this demo project anymore.

@nedtwigg I have seen your code which is supporting until eclipse version 4.5.2 and any version above goomph is throwing error. Can we incorporate Eclipse 4.20 as well?

**Comment by zeefahs13** [comment]
> > Happy to take a PR for it. Goomph definitely works with JDK 17, but we are not proactively updating this demo project anymore.
> 
> @nedtwigg I have seen your code which is supporting until eclipse version 4.5.2 and any version above goomph is throwing error. Can we incorporate Eclipse 4.20 as well?

@nedtwigg how about the gradle version, you are using 6+ which will not work with JDK 17. Do you have any plan stored in for latest release of JDK 17 for September 14 2021?

**Comment by nedtwigg** [comment]
https://github.com/diffplug/goomph/issues/35#issuecomment-883550242

**Comment by zeefahs13** [comment]
> [diffplug/goomph#35 (comment)](https://github.com/diffplug/goomph/issues/35#issuecomment-883550242)

Sorry I did not get you could you please elaborate
