### ISSUE TITLE
Support for Reproducible Version Qualifiers?

### ISSUE THREAD

**Issue by elmsley** [diffplug/gradle_and_eclipse_rcp#6]
Can this somehow support Reproducible Version Qualifiers (https://wiki.eclipse.org/Tycho/Reproducible_Version_Qualifiers) ?

**Comment by nedtwigg** [comment]
I haven't used RVQ before, but from reading that document it appears that RVQ has these features:
1. Generate the same version qualifier when building from the same git commit.
2. Only produce new artifact version when there are changes.
3. Guarantee consistent artifact id, version and contents.

Satisfying 1 can easily be done by generating the qualifier from the git commit SHA.  Satisfying 2 would be harder, but possible, by generating the qualifier from a hash of the jar file's content.  I think that 3 is ill-defined.

The qualifier is generated by the `bndmanifest` plugin, whose javadoc are [here](https://diffplug.github.io/goomph/javadoc/3.0.4/com/diffplug/gradle/osgi/BndManifestPlugin.html).

The current logic for generating the qualifier is [here](https://github.com/diffplug/goomph/blob/f250941449afccbfeae7c019ba328f73ba65df5c/src/main/java/com/diffplug/gradle/osgi/BndManifestPlugin.java#L166-L175).

Depending on your requirements, we could add a flag to the existing bndmanifest plugin, something like `qualifierFromGitHash = true`, to easily meet requirement 1.  If you need something more complicated, then it would probably make sense to make a new plugin.

**Comment by nedtwigg** [comment]
Feel free to reopen if there's future interest.
