### ISSUE TITLE
Include GEF into eclipse-deps

### ISSUE THREAD

**Issue by marve11ous** [diffplug/gradle_and_eclipse_rcp#8]
Is it possible to include GEF into such eclipse application somehow to have access org.eclipse.gef, org.eclipse.draw2d etc in dependencies like "compile 'eclipse-deps:org.eclipse.gef:+'"?
I've tried to add feature into target.p2 configuration, but it doesn't work.

**Comment by nedtwigg** [comment]
You need to add a GEF update site, listed here: https://projects.eclipse.org/projects/tools.gef/downloads

Example:

```gradle
p2AsMaven {
    // the maven group they shall have
    group 'gef', {
        // the repositories and artifacts to download
        repo 'http://download.eclipse.org/tools/gef/updates/legacy/releases/3.10.1_gef-maintenance_1205/'
        // add the plugins
        iu 'org.eclipse.gef'
        iu 'org.eclipse.gef.source'
        // or the features
        feature 'org.eclipse.gef'
    }
}
```

It will go faster if you add a repository for a specific version (as I did in the example) rather than using the root update site listed on the project page.
