### ISSUE TITLE
Building IDE-as-artifact fails with an exception

### ISSUE THREAD

**Issue by breandan** [diffplug/gradle_and_eclipse_rcp#9]
When I run `./gradlew ide`, the build fails with [an error](https://github.com/diffplug/gradle-and-eclipse-rcp/files/681567/error.txt).

**Comment by breandan** [comment]
Whoops, downgrading to Java 8 solves this issue.

**Comment by nedtwigg** [comment]
I think OSGi and Java 9 will have some brawling to do at some point in the future :)
